import LocalFont from 'next/font/local'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../styles/main.css"
import "../styles/sub.css"
import Header from "./components/Header.js";

const myFont = LocalFont({
  src : [
    {path : '../public/fonts/Paperlogy-4Regular.woff2', weight : '400', style : 'normal'},
    {path : '../public/fonts/Paperlogy-7Bold.woff2', weight : '700', style : 'normal'},
    {path : '../public/fonts/Paperlogy-8ExtraBold.woff2', weight : '800', style : 'normal'},
  ],
  display : 'swap',
  fallback : ['sans-serif']
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={`${myFont.className} ${geistSans.variable} ${geistMono.variable}`}>
        <div id="all-container">
          <Header />
          <main>
            {children}
          </main>
        </div>
        </body>
    </html>
  );
}
